services:
  blog:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NOTION_API_KEY
      - NOTION_DATA_SOURCE_ID
      - NOTION_AUTHORS_DATA_SOURCE_ID
      - TOKEN_FOR_REVALIDATE
      - NEXT_PUBLIC_GA_ID
    restart: unless-stopped
